push ebp;
mov ebp, esp;
sub esp, 0x98;
mov dword [esp + 8], 0x44;
mov dword [esp + 4], 0;
lea eax, [ebp - 0x5c];
mov dword [esp], eax;
call sym._memset;
mov dword [esp + 8], 0x10;
mov dword [esp + 4], 0;
lea eax, [ebp - 0x18];
mov dword [esp], eax;
call sym._memset;
mov dword [ebp - 0x5c], 0x44;
lea eax, [ebp - 0x18];
mov dword [esp + 0x24], eax;
lea eax, [ebp - 0x5c];
mov dword [esp + 0x20], eax;
mov dword [esp + 0x1c], 0;
mov dword [esp + 0x18], 0;
mov dword [esp + 0x14], 0;
mov dword [esp + 0x10], 0;
mov dword [esp + 0xc], 0;
mov dword [esp + 8], 0;
mov dword [esp + 4], 0;
mov dword [esp], str.c:_windows_system32_calc.exe;
mov eax, dword [sym.imp.KERNEL32.dll_CreateProcessA];
call eax;
sub esp, 0x28;
nop;
leave;
ret;
push ebp;
mov ebp, esp;
and esp, 0xfffffff0;
call sym.___main;
call sym._sc;
mov eax, 0;
leave;
ret;

